//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTEs2it.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class amigos
    {
        public int AmigoID { get; set; }
        [DisplayName("Nome: ")]
        public string NM_Amigo { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
