//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTEs2it.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class jogos
    {
        public int JogoID { get; set; }
        [DisplayName("Nome do Jogo: ")]
        public string Nome_Jogo { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SN_Emprestado { get; set; }
        [DisplayName("Emprestado para: ")]
        public string NM_Amigo { get; set; }
    }
}
