//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTEs2it.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        public int UserID { get; set; }
        [DisplayName("Usuário: ")]
        [Required(ErrorMessage = "Usuário é um campo Obrigatório")]
        public string Usuario { get; set; }
        public string Nome { get; set; }
        [DisplayName("Senha: ")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Senha é um campo Obrigatório")]
        public string Senha { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
